server:
    port: 2003
spring:
   application:
       name: badminton
   datasource:
       url: jdbc:mysql://localhost:3306/badminton
       username: root
       password: 1234
   redis:
     host: localhost
     port: 6379
